### ISSUE TITLE
Plugin will break sync if installed on two separate computers

### ISSUE THREAD

**Issue by laurent22** [BeatLink/joplin-plugin-untagged#1]
Let's say I do this:

- Install plugin on device 1 - new tag with ID '756e7461676765640000000000000000' is created
- Install plugin on device 2 - new tag with ID '756e7461676765640000000000000000' is created
- Now sync device 1 and device 2 - you'll end up with a unique constraint violation on the tag ID

In general it's not a good idea to set fixed IDs as you'll end up having issues with sync sooner or later.

A better way would be to use a pre-defined tag title, which it seem you are already doing? Even this way, you might want to consider what happens in the above scenario and the user ends up with two automatically created tags with the same title. In this case, maybe you'll want to merge all notes into one tag, and delete the extra one.

**Comment by BeatLink** [comment]
I'll work on it.

**Comment by BeatLink** [comment]
Fixed by https://github.com/BeatLink/joplin-plugin-untagged/commit/e64fb2a08fcb6c3b2eb8d2f5c3ff3fd4cc8887e5
